# Generated by Django 4.1.7 on 2023-04-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homework_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
